# Generated by Django 4.0.1 on 2023-06-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, unique=True, verbose_name='유저아이디')),
                ('user_email', models.EmailField(max_length=70, unique=True, verbose_name='유저 이메일')),
                ('user_pw', models.CharField(max_length=50, verbose_name='유저비밀번호')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저',
                'db_table': 'user',
            },
        ),
    ]
